# Default values for data-pipeline-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: ""
imagePullSecret: ""
deployment: ""

slot2:
  enabled: false

slot1:
  enabled: false

input_reader:
  name: input_reader
  # tag: 
  imagePullPolicy: IfNotPresent
  replicaCount: 2
  env:
    MESSAGING_TYPE: "" # kafka or eventhub
    # eventhub
    AZURE_STORAGE_ACCOUNT: ""
    AZURE_STORAGE_ACCESS_KEY: ""
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    LEASE_CONTAINER_NAME: ""
    # kafka
    KAFKA_TOPIC: ""
    KAFKA_CONSUMER_GROUP: ""
    KAFKA_ADDRESS: ""


output_writer:
  name: output_writer
  # tag:
  imagePullPolicy: IfNotPresent
  env:
    MESSAGING_TYPE: "" # kafka or eventhub
    # eventhub
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    # Kafka
    KAFKA_TOPIC: ""
    KAFKA_ADDRESS: ""
    OUTPUT_WRITER_PORT: ""

main_app: app_0

instance_apps:
  app_0:
    name: sample_app
    slot1_tag: latest
    slot2_tag: latest
    imagePullPolicy: IfNotPresent
    service:
      type: ClusterIP
      externalPort: 5000
      internalPort: 5000
    env:
      HOST: ""
      PORT: ""
      OUTPUT_URL: ""
      SCHEMA_FILEPATH: ""
