# Default values for data-pipeline-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

registry: ""
imagePullSecret: ""

namespace: default

input_reader:
  name: input_reader
  # tag: 
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  env:
    MESSAGING_TYPE: "" # kafka or eventhub
    # eventhub
    AZURE_STORAGE_ACCOUNT: ""
    AZURE_STORAGE_ACCESS_KEY: ""
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    LEASE_CONTAINER_NAME: ""
    APP_HOST: ""
    APP_PORT: ""
    # kafka
    KAFKA_TOPIC: ""
    KAFKA_CONSUMER_GROUP: ""
    APP_HOST: ""
    APP_PORT: ""
    KAFKA_ADDRESS: ""


output_writer:
  name: output_writer
  # tag: 
  imagePullPolicy: IfNotPresent
  env:
    MESSAGING_TYPE: "" # kafka or eventhub
    # eventhub
    EVENT_HUB_NAMESPACE: ""
    EVENT_HUB_NAME: ""
    EVENT_HUB_SAS_POLICY: ""
    EVENT_HUB_SAS_KEY: ""
    # Kafka
    KAFKA_TOPIC: ""
    KAFKA_ADDRESS: ""
    OUTPUT_WRITER_PORT: ""

instance_apps:
  - name: sample_app
    # tag: 
    imagePullPolicy: IfNotPresent
    deployment: "green"
    service:
      type: ClusterIP
    env:
      HOST: ""
      PORT: ""
      OUTPUT_URL: ""
      SCHEMA_FILEPATH: ""

  # Example of multiple apps
  - name: another_sample_app
    # tag: 
    imagePullPolicy: IfNotPresent
    service:
      type: ClusterIP
    deployment: "green"