# For each instance app, we create its own service
{{- $root := . -}}
{{- range $appName, $value := .Values.instance_apps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $appName | replace "_" "-"}}-{{ .tag }}-config
data:
{{- range $key, $value := .env }}
  {{ $key }}: {{ $value }}
{{- end }}
---
{{- end }}