version: "3.7"

services:
  tester-gen:
    build: 
      context: testgen/.
      dockerfile: Dockerfile
      args:
        CONTAINER_REG_AGOGOSML: ${CONTAINER_REG_AGOGOSML}
        TAG: latest
    ports:
     - "127.0.0.1:2000:5000"
    networks:
      mynet:
        aliases:
          - tester
    environment:
      MESSAGING_TYPE: ${MESSAGING_TYPE}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      EVENT_HUB_NAMESPACE: ${EVENT_HUB_NAMESPACE}
      EVENT_HUB_SAS_POLICY: ${EVENT_HUB_SAS_POLICY}
      EVENT_HUB_NAME_INPUT: ${EVENT_HUB_NAME_INPUT}
      EVENT_HUB_NAME_OUTPUT: ${EVENT_HUB_NAME_OUTPUT}
      LEASE_CONTAINER_NAME_OUTPUT: ${LEASE_CONTAINER_NAME_OUTPUT}
      APP_HOST: sample
      APP_PORT: 3000
      OUTPUT_WRITER_PORT: 6000
      OUTPUT_WRITER_HOST: output
      TEST_GEN_PORT: 2000
      TEST_GEN_HOST: 127.0.0.1
      EVENT_HUB_SAS_KEY_INPUT:
      EVENT_HUB_SAS_KEY_OUTPUT:
      AZURE_STORAGE_ACCESS_KEY:
      #kafka config
      KAFKA_TOPIC_INPUT: ${KAFKA_TOPIC_INPUT}
      KAFKA_TOPIC_OUTPUT: ${KAFKA_TOPIC_OUTPUT}
      KAFKA_TIMEOUT: ${KAFKA_TIMEOUT}
      KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
      KAFKA_ADDRESS: ${KAFKA_ADDRESS}
      EVENTHUB_KAFKA_CONNECTION_STRING: ${EVENTHUB_KAFKA_CONNECTION_STRING}
      SSL_CERT_LOCATION: ${SSL_CERT_LOCATION}

networks:
  mynet:
