apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-input-reader-config
data:
  MESSAGING_TYPE: {{ quote .Values.input_reader.env.MESSAGING_TYPE }}
  AZURE_STORAGE_ACCOUNT: {{ quote .Values.input_reader.env.AZURE_STORAGE_ACCOUNT }}
  AZURE_STORAGE_ACCESS_KEY: {{ quote .Values.input_reader.env.AZURE_STORAGE_ACCESS_KEY }}
  EVENT_HUB_NAMESPACE: {{ quote .Values.input_reader.env.EVENT_HUB_NAMESPACE }}
  EVENT_HUB_NAME: {{ quote .Values.input_reader.env.EVENT_HUB_NAME }}
  EVENT_HUB_SAS_POLICY: {{ quote .Values.input_reader.env.EVENT_HUB_SAS_POLICY }}
  EVENT_HUB_SAS_KEY: {{ quote .Values.input_reader.env.EVENT_HUB_SAS_KEY }}
  LEASE_CONTAINER_NAME: {{ quote .Values.input_reader.env.LEASE_CONTAINER_NAME }}
  APP_HOST: {{ quote .Values.main_app }}
  APP_PORT: {{ quote (index .Values.instance_apps .Values.main_app).service.externalPort }}
  KAFKA_TOPIC_INPUT: {{ quote .Values.input_reader.env.KAFKA_TOPIC_INPUT }}
  KAFKA_CONSUMER_GROUP: {{ quote .Values.input_reader.env.KAFKA_CONSUMER_GROUP }}
  KAFKA_ADDRESS: {{ quote .Values.input_reader.env.KAFKA_ADDRESS }}
  EVENTHUB_KAFKA_CONNECTION_STRING: {{ quote .Values.input_reader.env.EVENTHUB_KAFKA_CONNECTION_STRING }}
  KAFKA_TIMEOUT: {{ quote .Values.input_reader.env.KAFKA_TIMEOUT }}
  SSL_CERT_LOCATION: {{ quote .Values.input_reader.env.SSL_CERT_LOCATION }}
